server:
  port: 8769

eureka:
  instance:
    prefer-ip-address: true
      #该实例注册到服务中心的唯一ID
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      #与Eureka注册服务中心的通信zone和url地址
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: server-zuul
  cloud:
    client:
      ip-address: 127.0.0.1
  zipkin:
    #zipkinServer 的地址
    #base-url: http://localhost:9411
    sender:
      #zipkin链接方式
      type: rabbit #web
  sleuth:
    sampler:
      #指定采样请求的百分比（默认为 0.1，即 10%）
      probability : 1

zuul:
  ignoredServices: server-ribbon
  ignoredPatterns: /**/ignore/**
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    api-a:
      #服务映射的路径
      path: /api-a/**
      #路径
      #url: http://localhost:8764/
      #Eureka注册中心的服务的名称
      serviceId: server-ribbon
    api-b:
      #服务映射的路径
      path: /api-b/**
      #Eureka注册中心的服务的名称#
      serviceId: server-feign
#    api-c:
        #服务映射的路径
#        path: /api-c/**
        #serviceId名称
#        serviceId: users

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #hystrix超时时间
            timeoutInMilliseconds: 60000
# 在Ribbon中禁用Eureka使用
#ribbon:
#  eureka:
#    enabled: false
#users:
#  ribbon:
#    listOfServers: http://localhost:8762/,http://localhost:8763/
# ribbon