server:
  port: 8769

eureka:
  instance:
    prefer-ip-address: true
      #该实例注册到服务中心的唯一ID
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      #与Eureka注册服务中心的通信zone和url地址
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: server-zuul
  cloud:
    client:
      ip-address: 127.0.0.1
  zipkin:
    #zipkinServer 的地址
    #base-url: http://localhost:9411
    sender:
      #zipkin链接方式
      type: rabbit #web
  sleuth:
    sampler:
      #指定采样请求的百分比（默认为 0.1，即 10%）
      probability : 1

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    api-a:
      path: /api-a/**
      serviceId: server-ribbon
    api-b:
      path: /api-b/**
      serviceId: server-feign

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  eureka:
    enabled: false
server-ribbon:
  ribbon:
    listOfServers: localhost:8764