eureka:
  instance:
    prefer-ip-address: true
    #该实例注册到服务中心的唯一ID
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      #与Eureka注册服务中心的通信zone和url地址
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          #配置文件git地址
          uri: https://github.com/daiqianshi/cloud-config
          #配置文件搜索路径
          searchPaths: configs
          #用户名，公有库不需要
          username:
          #密码，公有库不需要
          password:
      # git分支
      label: master
    bus:
      enabled: true
      trace:
        enabled: true
    client:
      ip-address: 127.0.0.1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8890

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

