eureka:
  instance:
    prefer-ip-address: true
    #该实例注册到服务中心的唯一ID
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      #与Eureka注册服务中心的通信zone和url地址
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: server-feign
  cloud:
    client:
      ip-address: 127.0.0.1

server:
  port: 8765

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        #连接时间
        connectTimeout: 10000
        #超时时间
        readTimeout: 10000