server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    #该实例，相较于hostname是否优先使用IP
    prefer-ip-address: true
    #该实例注册到服务中心的唯一ID
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    register-with-eureka: false
    #与Eureka注册服务中心的通信zone和url地址
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka/
    #此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetch-registry: false
  server:
      #节点间的读数据连接超时时间
      peer-node-read-timeout-ms: 3000
      #服务端开启自我保护模式。无论什么情况，服务端都会保持一定数量的服务。避免client与server的网络问题，而出现大量的服务被清除。
      enable-self-preservation: true

spring:
  application:
    name: server-master
  cloud:
    client:
      ip-address: 127.0.0.1
